# Numpy
### numpy를 사용하는 이유
행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리이다.
numpy는 데이터 분석 및 과학적 수치 계산을 위한 함수들을 제공한다.
넘파이를 사용하기 위해서는 numpy 모듈을 import 해야한다.

import numpy as np



# 1차원
-숫자가 10과 같이 하나만 들어간다고 해도 [ ] 리스트로 한 번 씌우게 되면 차원이 생긴다.
-이때 1차원이 되는건데 numpy 에서 shape를 표현할 때 (1)이 아닌 (1,) 이런 식으로 표현하게 됨


In [3]:
import numpy as np
arr = np.array([5])
arr

array([5])

In [5]:
arr.shape # (1,) 1행의 행렬

(1,)

In [6]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
arr.shape # 1차원이지만 scalar가 3개 있다. 


(3,)

## 2차원
대괄호를 추가적으로 씌우면 차원이 추가적으로 하나 생김

In [8]:
arr = np.array([[1,2,3,]]) # value가 3개인 shape이 1개 있다는 의미
arr.shape
# 1행 3열의 행렬

(1, 3)

In [15]:
arr = np.array([[1,2,3,], [1,2,3], [1,2,3],[1,2,3]]) # 1차원이 3개가 모인다. 
arr.shape
# 4행 3열

(4, 3)

In [17]:
arr.ndim # .ndim : 차원을 반환

2

In [18]:
arr.size # .size : 배열 요소의 총 갯수 반환

12

### 다차원

In [29]:
arr = np.array([[[1],[2],[3]],[[1],[2],[3]],[[1],[2],[3]]])
arr # (3,3,1) 

array([[[1],
        [2],
        [3]],

       [[1],
        [2],
        [3]],

       [[1],
        [2],
        [3]]])

In [30]:
arr

(3, 3, 1)

### zeros & ones
0으로 채워진 numpy array를 만들 수 있다
간단하지만 유용하게 쓸 수 있다.

In [31]:
zeros = np.zeros([3,3]) # 0으로 채워진 3행 3열 행렬을 만든다.
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
zeros = np.zeros(1) # 
zeros

array([0.])

In [34]:
ones = np.ones([10]) # size가 10개인 ones
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
ones = np.ones([10,5]) # 10 * 5 ones
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [38]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [39]:
arr = np.arange(4,9) # 4~8까지 
arr

array([4, 5, 6, 7, 8])

In [40]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Index

In [42]:
nums = [1,2,3,4,5]

In [43]:
nums[2:] # list 와 같이 슬라이싱이 된다.

[3, 4, 5]

In [45]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr[1]

array([3, 4, 5])

In [46]:
arr[1][2]

5

In [47]:
arr[1,2]

5

### Slicing

In [49]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [50]:
arr[1:, 1:] # 2번째 행, 2번째 열

array([[4, 5],
       [7, 8]])

### Boolean Indexing

In [52]:
data = np.random.randn(3, 3)
data

array([[ 1.26982613,  0.73202142,  0.54966715],
       [-0.8514531 ,  0.27101881, -0.78036171],
       [-0.27198056, -1.51493914,  1.87203641]])

In [53]:
data <= 0

array([[False, False, False],
       [ True, False,  True],
       [ True,  True, False]])

In [54]:
data[data <= 0] = 1

In [55]:
data

array([[1.26982613, 0.73202142, 0.54966715],
       [1.        , 0.27101881, 1.        ],
       [1.        , 1.        , 1.87203641]])

### Broadcast

tensorflow 나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 한다.
 
broadcast는 연산하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때 이를 여러 복사를 하여 연산을 함

In [56]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [59]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
arr + np.array([1,2,3]) # 각 행마다 1,2,3씩 순서에 맞게 더해줌

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

### Math Function

In [61]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [62]:
arr + 1 # 결과값은 np.add(arr, 1) 와 같다

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.multiply(arr, 3) # 곱하기

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [66]:
arr = np.random.randint(2, size=27).reshape(3,3,3) 
'''
0부터 1까지의 숫자를 랜덤하게 size는 27만들고
reshape를 (3,3,3)으로 만들어라는 의미
'''

arr_2 = np.random.randint(2, size = 9).reshape(3,3)

In [67]:
arr

array([[[1, 1, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 1],
        [1, 0, 1]],

       [[1, 0, 0],
        [1, 0, 1],
        [0, 1, 0]]])

In [68]:
arr_2

array([[0, 1, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [70]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [71]:
np.sum(arr) # arr 의 값을 더한다.

12

In [72]:
np.sum(arr + arr_2) 

24

In [73]:
arr + arr_2

array([[[1, 2, 1],
        [0, 1, 0],
        [0, 0, 2]],

       [[1, 1, 1],
        [0, 2, 1],
        [1, 0, 2]],

       [[1, 1, 1],
        [1, 1, 1],
        [0, 1, 1]]])

In [74]:
np.max(arr + arr_2) # 가장 큰 값

2

In [75]:
np.min(arr + arr_2)

0

In [76]:
np.max(arr + arr_2, 0) # 2차원인 값들 중에서 가장 큰 값으로 0차원을 만들어준다.

array([[1, 2, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [77]:
np.mean(arr)

0.4444444444444444

In [79]:
arr_3 = np.array([1,6,3,7,2,9,0,2])
arr_3

array([1, 6, 3, 7, 2, 9, 0, 2])

In [80]:
np.argmax(arr_3) # 5번지 값이 가장 크다

5

In [81]:
np.argmin(arr_3) # 6번지 값이 가장 작다.

6

In [82]:
arr_4 = np.array([3,3,5,7,3,5,4,5])

In [84]:
np.unique(arr_4) # 고유한 값들만 모아서 반환하다.

array([3, 4, 5, 7])